### ISSUE TITLE
which branch of dynet to use?

### ISSUE THREAD

**Issue by ajaech** [neubig/modlm#2]
The README says to use the "v2" branch of dynet. As far as I can tell, there is no branch of dynet called "v2". I can't get this repo to build using the master branch of dynet.

**Comment by ajaech** [comment]
Update: I got it to build using the 61b55f375dbc6ed63f476e41d3de0e2696319f45 commit of dynet.

**Comment by neubig** [comment]
I just did a small update and it should work with the latest version of DyNet (04d6dbc82bb6358545be9c507485a4cb938f4416) now. Thanks for pointing this out!
